# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0c4212af29ef8f9bf13baf7d3df99f70b22920aba537d6392aabb0652e51f42046852d4e34d01fdc9c363eeaee6ffa2b3ec3e875450418475e6c490bb47832c

test:
  secret_key_base: d9b93509f9001a01d7d3058359a819fd224abb757af05c47c457b9fabace80f34a1e374d0ab0bb7b514e5cd2d021e4475c3f7f0a4754f2e53dad44e577b95b70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
